## Default values for snapagogo

snapagogo:
  api:
    image: ontoserver.azurecr.io/snapagogo-api:latest
    resources:
      cpu: 500m
      memory: 3Gi
      initialHeapSize: 2g
      maxHeapSize: 2g
      memorylimit: true
    hostNames:
      - api.snapagogo.app
    config:
      # This section is for server configuration via environment variables
      sentry.dsn:                                           https://5180085a05cdc11306020b69e139503b@o144408.ingest.sentry.io/4505673387343872
      ui.sentry.dsn:                                        https://7af28975eeab0c505ba856a7df34d9c7@o144408.ingest.sentry.io/4505673382035456
      sentry.environment:                                   K8S
      spring.security.oauth2.resourceserver.jwt.issuer-uri: https://auth.ontoserver.csiro.au/auth/realms/aehrc
      snap2snomed.security.authDomainUrl:                   https://auth.ontoserver.csiro.au/auth/realms/aehrc/protocol/openid-connect
      spring.datasource.driverClassName:                    software.aws.rds.jdbc.mysql.Driver
      spring.datasource.username:                           root
      snap2snomed.security.adminGroup:                      /snapagogoadmin
      snap2snomed.security.clientId:                        snapagogo
      snap2snomed.security.audience:                        snapagogo
      snap2snomed.privacyPolicyUrl:                         https://www.csiro.au/en/about/Policies/Privacy
      snap2snomed.targetCodeSystems:                        http://snomed.info/sct,http://loinc.org,http://www.nlm.nih.gov/research/umls/rxnorm
      snap2snomed.defaultTerminologyServer.url:             https://r4.ontoserver.csiro.au/fhir
  ui:
    image: ontoserver.azurecr.io/snapagogo-api:latest
    apiBaseUrl: https://api.snapagogo.app
    hostNames:
      - www.snapagogo.app
      - snapagogo.app
    resources:
      cpu: 500m
      memory: 256M
      memorylimit: false

  database:
    password: setonthecommandline
    name: s2s


  highPriority: false

  nodeselector: {}

  tolerations:
    - key: "kubernetes.azure.com/scalesetpriority"
      operator: "Equal"
      value: "spot"
      effect: "NoSchedule"


gateway:
  enabled: true
  annotations: {}
  infrastructureAnnotations:
    service.beta.kubernetes.io/azure-dns-label-name: snapagogo
  className: envoy-gateway-class-metrics
  hostNames:
    - snapagogo.app
    - api.snapagogo.app
    - www.snapagogo.app
  listenerPortHttp: 80
  listenerPortSecure: 443
  controlPlaneNamespace: envoy-gateway-system
  requestTimeout: 3s

nginx-ingress:
  controller:
    enableSnippets: true
    enableCertManager: true
    service:
      annotations:
        service.beta.kubernetes.io/azure-dns-label-name: snapagogo
    # nginx 1.0.2
    ingressClass:
      name: snapagogo-nginx
      create: true

ingress:
  className: snapagogo-nginx
  nginx:
    enabled: false
    sslRedirect: true

certmanager:
  enabled: true
  email: ontoserver-support@csiro.au

tls:
  enabled: true
  certRef: snapagogo-tls-secret

repoSecret:
  enabled: false
  dockerconfigjson: # Docker config Json goes here if repo secret is enabled (e.g. for Quay IO images)